# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/zusys_gig_ethernet_pcs_pma_0_0.xci
# IP: The module: 'zusys_gig_ethernet_pcs_pma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/zusys_gig_ethernet_pcs_pma_0_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_gig_ethernet_pcs_pma_0_0_gt || ORIG_REF_NAME==zusys_gig_ethernet_pcs_pma_0_0_gt} -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/synth/zusys_gig_ethernet_pcs_pma_0_0_gt_ooc.xdc

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/synth/zusys_gig_ethernet_pcs_pma_0_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zusys_gig_ethernet_pcs_pma_0_0_gt || ORIG_REF_NAME==zusys_gig_ethernet_pcs_pma_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/zusys_gig_ethernet_pcs_pma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/zusys_gig_ethernet_pcs_pma_0_0.xci
# IP: The module: 'zusys_gig_ethernet_pcs_pma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/zusys_gig_ethernet_pcs_pma_0_0_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_gig_ethernet_pcs_pma_0_0_gt || ORIG_REF_NAME==zusys_gig_ethernet_pcs_pma_0_0_gt} -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/synth/zusys_gig_ethernet_pcs_pma_0_0_gt_ooc.xdc

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/synth/zusys_gig_ethernet_pcs_pma_0_0_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zusys_gig_ethernet_pcs_pma_0_0_gt || ORIG_REF_NAME==zusys_gig_ethernet_pcs_pma_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/zusys_gig_ethernet_pcs_pma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
