#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : zusys.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Dec 31 10:44:51 +0900 2019
# SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: zusys.sh [-help]
# usage: zusys.sh [-lib_map_path]
# usage: zusys.sh [-noclean_files]
# usage: zusys.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'zusys.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 zynq_ultra_ps_e_vip_v1_0_3 gtwizard_ultrascale_v1_7_4 gig_ethernet_pcs_pma_v16_1_4 xlconstant_v1_1_5)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "zusys.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ipshared/c35f/src/SC0808BF.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_SC0808BF_0_0/sim/zusys_SC0808BF_0_0.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/5e77/hdl/axis_live_audio_v1_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_axis_live_audio_0_0/sim/zusys_axis_live_audio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ip/zusys_proc_sys_reset_0_0/sim/zusys_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_proc_sys_reset_1_0/sim/zusys_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_vio_general_0/sim/zusys_vio_general_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_zynq_ultra_ps_e_0_0/sim/zusys_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ipshared/d3ec/src/ddrspi_master.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/d3ec/src/ddsrpi_slave.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/d3ec/src/RGPIO_top.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_RGPIO_Master_CPLD_0/sim/zusys_RGPIO_Master_CPLD_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_RGPIO_Slave_CPLD_0/sim/zusys_RGPIO_Slave_CPLD_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_vio_rgpio_0/sim/zusys_vio_rgpio_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/sim/zusys_gig_ethernet_pcs_pma_0_0_gt_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/sim/zusys_gig_ethernet_pcs_pma_0_0_gt_gtwizard_gthe4.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/sim/zusys_gig_ethernet_pcs_pma_0_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/ip_0/sim/zusys_gig_ethernet_pcs_pma_0_0_gt.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work gig_ethernet_pcs_pma_v16_1_4 $vhdlan_opts \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/494d/hdl/gig_ethernet_pcs_pma_v16_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gig_ethernet_pcs_pma_v16_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/494d/hdl/gig_ethernet_pcs_pma_v16_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_resets.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_clocking.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_support.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_reset_sync.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_sync_block.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/transceiver/zusys_gig_ethernet_pcs_pma_0_0_transceiver.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0_block.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_gig_ethernet_pcs_pma_0_0/synth/zusys_gig_ethernet_pcs_pma_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/ef07/hdl" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../StarterKit.srcs/sources_1/bd/zusys/ipshared/0000/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_xlconstant_2_1/sim/zusys_xlconstant_2_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_xlconstant_2_2/sim/zusys_xlconstant_2_2.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_xlconstant_2_3/sim/zusys_xlconstant_2_3.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_signal_detect_0/sim/zusys_signal_detect_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_signal_detect_1/sim/zusys_signal_detect_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_an_config_vector_0/sim/zusys_an_config_vector_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/sim/bd_71cc_ila_lib_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_system_ila_0_0/bd_0/sim/bd_71cc.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_system_ila_0_0/sim/zusys_system_ila_0_0.v" \
    "$ref_dir/../../../bd/zusys/sim/zusys.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.zusys xil_defaultlib.glbl -o zusys_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./zusys_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./zusys.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key zusys_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc zusys_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./zusys.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: zusys.sh [-help]\n\
Usage: zusys.sh [-lib_map_path]\n\
Usage: zusys.sh [-reset_run]\n\
Usage: zusys.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
