# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/zusys_system_ila_0_0.xci
# IP: The module: 'zusys_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/bd_71cc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_71cc || ORIG_REF_NAME==bd_71cc} -quiet] -quiet

# IP: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/bd_71cc_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_71cc_ila_lib_0 || ORIG_REF_NAME==bd_71cc_ila_lib_0} -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_71cc_ila_lib_0 || ORIG_REF_NAME==bd_71cc_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_71cc_ila_lib_0 || ORIG_REF_NAME==bd_71cc_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/bd_71cc_ila_lib_0_ooc.xdc

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/bd_71cc_ooc.xdc

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/zusys_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/zusys_system_ila_0_0.xci
# IP: The module: 'zusys_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/bd_71cc.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_71cc || ORIG_REF_NAME==bd_71cc} -quiet] -quiet

# IP: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/bd_71cc_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_71cc_ila_lib_0 || ORIG_REF_NAME==bd_71cc_ila_lib_0} -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_71cc_ila_lib_0 || ORIG_REF_NAME==bd_71cc_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_71cc_ila_lib_0 || ORIG_REF_NAME==bd_71cc_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/ip/ip_0/bd_71cc_ila_lib_0_ooc.xdc

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/bd_0/bd_71cc_ooc.xdc

# XDC: d:/TRENZ_TE0808/TE0808_Ethernet_2018.2/StarterKit/vivado/StarterKit.srcs/sources_1/bd/zusys/ip/zusys_system_ila_0_0/zusys_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
